"""reconciliation tables

Revision ID: 0462b203d108
Revises: 04a06f4ac27c
Create Date: 2026-07-10 10:52:47.081915

"""
from alembic import op
import sqlalchemy as sa


revision = '0462b203d108'
down_revision = '04a06f4ac27c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_asset_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('custody_ticker', sa.String(length=64), nullable=False),
    sa.Column('asset_symbol', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'custody_ticker')
    )
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('period_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('ledger_tx_ids', sa.JSON(), nullable=False),
    sa.Column('custody_entry_ids', sa.JSON(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_results')
    op.drop_table('reconciliation_runs')
    op.drop_table('custody_asset_mapping')
    # ### end Alembic commands ###
