"""custody statements and entries

Revision ID: 04a06f4ac27c
Revises: d8e121a15f47
Create Date: 2026-07-10 09:47:46.837110

"""
from alembic import op
import sqlalchemy as sa


revision = '04a06f4ac27c'
down_revision = 'd8e121a15f47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.String(length=128), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('period_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'statement_id')
    )
    op.create_table('custody_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(length=128), nullable=False),
    sa.Column('statement_pk', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('operation_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRADE', 'FEE', 'TRANSFER_INTERNAL', 'OTHER', name='custodyoperationtype', native_enum=False), nullable=False),
    sa.Column('counterparty_ref', sa.String(length=256), nullable=True),
    sa.Column('external_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_line', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['statement_pk'], ['custody_statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_pk', 'entry_id')
    )
    # Журнал неизменяемости: выписки — первичка, как ответы нод (п. 5 спеки).
    # Функция connector_forbid_change() создана миграцией a90d41f2b7c1 (PG-only).
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE TRIGGER trg_custody_statements_immutable "
            "BEFORE UPDATE OR DELETE ON custody_statements "
            "FOR EACH ROW EXECUTE FUNCTION connector_forbid_change();"
        )
        op.execute(
            "CREATE TRIGGER trg_custody_entries_immutable "
            "BEFORE UPDATE OR DELETE ON custody_entries "
            "FOR EACH ROW EXECUTE FUNCTION connector_forbid_change();"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "DROP TRIGGER IF EXISTS trg_custody_entries_immutable ON custody_entries;"
        )
        op.execute(
            "DROP TRIGGER IF EXISTS trg_custody_statements_immutable "
            "ON custody_statements;"
        )
    op.drop_table('custody_entries')
    op.drop_table('custody_statements')
