"""Add AssetLegalProfile and Operation links (G3, G4)

Revision ID: 0fe9b49f63a1
Revises: 73899289a7b4
Create Date: 2026-09-02 11:31:05.459178

"""
from alembic import op
import sqlalchemy as sa


revision = '0fe9b49f63a1'
down_revision = '73899289a7b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ADOPTED', 'OFFICIALLY_PUBLISHED', 'EFFECTIVE', 'SUPERSEDED', name='regulatoryrulestatus', native_enum=False), nullable=False),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('officially_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('document_ref', sa.String(length=256), nullable=False),
    sa.Column('xml_official', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('asset_legal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('DIGITAL_CURRENCY', 'FOREIGN_DIGITAL_INSTRUMENT', name='assetlegalcategory', native_enum=False), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('HYPOTHESIS', 'APPROVED_BY_COUNSEL', 'SUPERSEDED', name='assetlegalprofilestatus', native_enum=False), nullable=False),
    sa.Column('counsel_opinion_ref', sa.String(length=256), nullable=False),
    sa.Column('fifo_enabled', sa.Boolean(), nullable=False),
    sa.Column('tax_regime', sa.String(length=128), nullable=False),
    sa.Column('revaluation_strategy', sa.String(length=128), nullable=False),
    sa.Column('regulatory_rule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['regulatory_rule_id'], ['regulatory_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('regulatory_rule_id', sa.Integer(), nullable=True),
    sa.Column('regulatory_rule_version', sa.String(length=64), nullable=False),
    sa.Column('rule_status_at_processing', sa.String(length=64), nullable=False),
    sa.Column('asset_legal_profile_id', sa.Integer(), nullable=True),
    sa.Column('report_status', sa.Enum('NOT_APPLICABLE', 'PENDING', 'REPORTED', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('operation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_channel', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_legal_profile_id'], ['asset_legal_profiles.id'], ),
    sa.ForeignKeyConstraint(['regulatory_rule_id'], ['regulatory_rules.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('expected_payments', sa.Column('route', sa.Enum('DIRECT', 'BANK', 'AGENT', 'EXCHANGE_ORGANIZATION', 'DIGITAL_DEPOSITORY', name='paymentroute', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expected_payments', 'route')
    op.drop_table('operations')
    op.drop_table('asset_legal_profiles')
    op.drop_table('regulatory_rules')
    # ### end Alembic commands ###
