"""expected payments

Revision ID: 2243a1fabec4
Revises: b81d5fbc2c1e
Create Date: 2026-07-13 05:45:33.094347

"""
from alembic import op
import sqlalchemy as sa


revision = '2243a1fabec4'
down_revision = 'b81d5fbc2c1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('to_address', sa.String(length=128), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('tolerance', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('status', sa.Enum('PENDING_AML', 'AML_APPROVED', 'AML_REVIEW', 'AML_REJECTED', 'SENT', 'MATCHED', 'EXPIRED', name='expectedpaymentstatus', native_enum=False), nullable=False),
    sa.Column('aml_screening_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aml_screening_id'], ['aml_screenings.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'to_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expected_payments')
    # ### end Alembic commands ###
