"""wallet sync cursor

Revision ID: 8e8be88cd3ce
Revises: 91fc6b2c79da
Create Date: 2026-07-09 11:03:45.331151

"""
from alembic import op
import sqlalchemy as sa


revision = '8e8be88cd3ce'
down_revision = '91fc6b2c79da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('last_scanned_block', sa.Integer(), nullable=True))
    op.add_column('wallets', sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'last_scanned_at')
    op.drop_column('wallets', 'last_scanned_block')
    # ### end Alembic commands ###
