"""invoice onec_ref

Revision ID: 91fc6b2c79da
Revises: 275e83aa6f57
Create Date: 2026-07-09 09:13:54.751660

"""
from alembic import op
import sqlalchemy as sa


revision = '91fc6b2c79da'
down_revision = '275e83aa6f57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default='' — колонка NOT NULL добавляется и на непустую таблицу
    op.add_column(
        'invoices',
        sa.Column('onec_ref', sa.String(length=64), nullable=False, server_default=''),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'onec_ref')
    # ### end Alembic commands ###
