"""aml screenings

Revision ID: b81d5fbc2c1e
Revises: f7fb6ffad475
Create Date: 2026-07-13 05:26:16.703682

"""
from alembic import op
import sqlalchemy as sa


revision = 'b81d5fbc2c1e'
down_revision = 'f7fb6ffad475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aml_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aml_screenings_address'), 'aml_screenings', ['address'], unique=False)
    # Журнал неизменяемости: скрининги — доказательная первичка, как ответы
    # нод и выписки (функция connector_forbid_change — миграция a90d41f2b7c1).
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE TRIGGER trg_aml_screenings_immutable "
            "BEFORE UPDATE OR DELETE ON aml_screenings "
            "FOR EACH ROW EXECUTE FUNCTION connector_forbid_change();"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_aml_screenings_immutable ON aml_screenings;")
    op.drop_index(op.f('ix_aml_screenings_address'), table_name='aml_screenings')
    op.drop_table('aml_screenings')
    # ### end Alembic commands ###
