"""revaluations

Revision ID: d8e121a15f47
Revises: ed3d85569af8
Create Date: 2026-07-10 07:10:40.289325

"""
from alembic import op
import sqlalchemy as sa


revision = 'd8e121a15f47'
down_revision = 'ed3d85569af8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('book_cost_rub', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('market_rub', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('difference_rub', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('delta_rub', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('rate_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['rate_snapshot_id'], ['rate_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'as_of')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revaluations')
    # ### end Alembic commands ###
