"""regulation fields kvvo crypto_address kpp

Revision ID: f7fb6ffad475
Revises: d8e121a15f47
Create Date: 2026-07-13 04:27:04.275282

"""
from alembic import op
import sqlalchemy as sa


revision = 'f7fb6ffad475'
down_revision = 'd8e121a15f47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('kvvo', sa.String(length=8), nullable=False, server_default=''))
    op.add_column('invoices', sa.Column('crypto_address', sa.String(length=128), nullable=False, server_default=''))
    op.add_column('organizations', sa.Column('kpp', sa.String(length=9), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'kpp')
    op.drop_column('invoices', 'crypto_address')
    op.drop_column('contracts', 'kvvo')
    # ### end Alembic commands ###
